# Generated by Django 3.0.5 on 2020-05-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipno', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='at2',
            new_name='accepted_at',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='at1',
            new_name='suggested_at',
        ),
        migrations.AddField(
            model_name='match',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
