# Generated by Django 3.0.5 on 2020-05-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200512_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
