# Generated by Django 3.0.5 on 2020-05-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200512_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
